shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - devtools

onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - protobufjs
  - unrs-resolver
  - vue-demi
  - workerd

trustPolicyIgnoreAfter: 262800
