import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import Module from '../../../src/module'

const __dirname = dirname(fileURLToPath(import.meta.url))

export default defineNuxtConfig({
  modules: [Module],
  compatibilityDate: '2025-10-10',

  nitro: {
    preset: 'cloudflare-durable',
    experimental: {
      websocket: true,
    },
  },

  skewProtection: {
    debug: true,
    updateStrategy: 'ws',
    connectionTracking: true,
    // Use fs storage for build-time asset bundling (cloudflare-kv-binding only works at runtime)
    storage: {
      driver: 'fs',
      base: `${__dirname}/.skew-storage`,
    },
    retentionDays: 1,
    maxNumberOfVersions: 3,
  },

  // runtimeConfig.app.buildId is auto-generated by Nuxt
})
