import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

export default defineNuxtConfig({
  modules: ['../../../src/module'],
  compatibilityDate: '2025-10-10',

  nitro: {
    preset: 'cloudflare-durable',
    experimental: {
      websocket: true,
    },
  },

  skewProtection: {
    debug: true,
    checkForUpdateStrategy: 'ws',
    storage: {
      driver: 'cloudflare-kv-binding',
      binding: 'SKEW_STORAGE',
      namespaceId: '3de5b8fa99f545c7a78f40ea3fc71646',
    },
    retentionDays: 1,
    maxNumberOfVersions: 3,
  },

  // runtimeConfig.app.buildId is auto-generated by Nuxt
})
