import type { CookieSerializeOptions } from 'cookie-es'
import type { BroadcastFn, SkewAdapter } from './runtime/adapters/types'
import type { NuxtSkewProtectionRuntimeConfig } from './runtime/types'
import { existsSync } from 'node:fs'
import {
  addComponent,
  addImports,
  addPlugin,
  addServerHandler,
  addTemplate,
  addTypeTemplate,
  createResolver,
  defineNuxtModule,
  hasNuxtModule,
  tryResolveModule,
} from '@nuxt/kit'
import { colors } from 'consola/utils'
import { installNuxtSiteConfig } from 'nuxt-site-config/kit'
import { readPackageJSON } from 'pkg-types'
import { hookNuxtSeoProLicense, isStaticPreset, resolveNitroPreset } from './kit'
import { logger } from './logger'
import { resolveBuildTimeDriver } from './unstorage/utils'
import { isSkewAdapter } from './utils'
import { createAssetManager } from './utils/version-manager'

export interface ModuleOptions {
  /**
   * Storage configuration for versioned assets
   */
  storage?: (Record<string, any> & {
    driver: string
  })
  /**
   * How long to retain old versions (in days)
   * @default 30
   */
  retentionDays?: number
  /**
   * Maximum number of versions to retain
   * @default 10
   */
  maxNumberOfVersions?: number
  /**
   * Strategy for checking for version updates
   * - 'polling': Nuxt's native polling of builds/latest.json (default)
   * - 'sse': Use Server-Sent Events for real-time updates
   * - 'ws': Use WebSocket (requires cloudflare-durable preset or experimental.websocket)
   * - SkewAdapter: Third-party WebSocket provider (Pusher, Ably)
   * @default Static: 'polling', Node: 'sse', Cloudflare: 'ws'
   */
  updateStrategy?: 'polling' | 'sse' | 'ws' | SkewAdapter
  /**
   * Cookie configuration for storing deployment version
   */
  cookie?: false | Omit<CookieSerializeOptions, 'encode'> & {
    /**
     * Cookie name for storing deployment version
     * @default '__nkpv'
     */
    name?: string
  }
  /**
   * Bundle previous deployment chunks to support users on old versions
   * When enabled, old build assets are stored and served to users who haven't refreshed
   * @default true
   * @note Automatically disabled when using CDN URL
   */
  bundlePreviousDeploymentChunks?: boolean
  /**
   * Enable or disable the module
   * @default true
   */
  enabled: boolean
  /**
   * Enable debug logging
   * @default false
   */
  debug?: boolean
}

export interface ModulePublicRuntimeConfig {
  skewProtection: NuxtSkewProtectionRuntimeConfig
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-skew-protection',
    compatibility: {
      nuxt: '>=4.0.0',
    },
    configKey: 'skewProtection',
  },
  defaults: {
    retentionDays: 30,
    maxNumberOfVersions: 10,
    bundlePreviousDeploymentChunks: true,
    cookie: {
      name: '__nkpv',
      path: '/',
      sameSite: 'strict' as const,
      maxAge: 60 * 60 * 24 * 60, // 60 days
    },
    storage: {
      driver: 'fs',
      base: 'node_modules/.cache/nuxt-seo/skew-protection',
    },
    debug: false,
  },
  async setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)
    const { version } = await readPackageJSON(resolver.resolve('../package.json'))
    logger.level = (options.debug || nuxt.options.debug) ? 4 : 3
    if (options.enabled === false) {
      logger.debug('The module is disabled, skipping setup.')
      return
    }

    await installNuxtSiteConfig()
    hookNuxtSeoProLicense()
    // Add runtime config for client access to module options
    nuxt.options.runtimeConfig.public = nuxt.options.runtimeConfig.public || {}
    // @ts-expect-error untyped
    nuxt.options.runtimeConfig.public.skewProtection = {
      cookie: options.cookie as Required<NuxtSkewProtectionRuntimeConfig['cookie']>,
      debug: options.debug,
      version,
    } as Required<NuxtSkewProtectionRuntimeConfig>

    // Detect Nitro preset
    const nitroPreset = resolveNitroPreset(nuxt.options.nitro)

    // Detect NuxtHub and guide users on KV configuration
    const isNuxtHub = hasNuxtModule('@nuxthub/core')
    if (isNuxtHub && options.storage?.driver === 'cloudflare-kv-binding' && !options.storage.namespaceId) {
      logger.error('NuxtHub detected with cloudflare-kv-binding driver but no namespaceId configured.')
      logger.info('Learn more: https://nuxtseo.com/docs/skew-protection/guides/cloudflare')
      throw new Error('namespaceId required for cloudflare-kv-binding driver with NuxtHub')
    }

    // Add TypeScript types
    addTypeTemplate({
      filename: 'types/nuxt-skew-protection.d.ts',
      getContents: () => {
        return `// Generated by nuxt-skew-protection
declare module '#app' {
  interface RuntimeNuxtHooks {
    'skew-protection:chunks-outdated': (payload: ChunksOutdatedPayload) => void | Promise<void>
  }
  interface NuxtApp {
    $skewProtectionBuildId: Ref<string | undefined>
    $skewProtectionCookie: Ref<string | undefined>
  }
  interface NuxtAppManifestMeta {
    skewProtection?: {
      versions?: Record<string, {
        timestamp: string
        expires: string
        assets: string[]
        deletedChunks?: string[]
      }>
    }
  }
}

declare module 'nuxt/app' {
  interface RuntimeNuxtHooks {
    'skew-protection:chunks-outdated': (payload: ChunksOutdatedPayload) => void | Promise<void>
  }
  interface NuxtApp {
    $skewProtectionBuildId: Ref<string | undefined>
    $skewProtectionCookie: Ref<string | undefined>
  }
  interface NuxtAppManifestMeta {
    skewProtection?: {
      versions?: Record<string, {
        timestamp: string
        expires: string
        assets: string[]
        deletedChunks?: string[]
      }>
    }
  }
}

export {}
`
      },
    }, {
      nuxt: true,
    })

    addComponent({
      name: 'SkewNotification',
      filePath: resolver.resolve(`./runtime/app/components/SkewNotification.vue`),
    })

    // add useSkewProtection composable import
    addImports({
      name: 'useSkewProtection',
      from: resolver.resolve('./runtime/app/composables/useSkewProtection'),
    })

    // Initialize buildId state for SSR->client hydration
    addPlugin({
      src: resolver.resolve('./runtime/app/plugins/init-build-id'),
    })

    // add alias for nuxt-skew-protection/server -> src/runtime/server
    nuxt.options.alias['nuxt-skew-protection/server'] = resolver.resolve('./runtime/server')
    if (options.storage?.driver) {
      // Mount storage for runtime access
      nuxt.options.nitro = nuxt.options.nitro || {}
      nuxt.options.nitro.storage = nuxt.options.nitro.storage || {}
      nuxt.options.nitro.storage['skew-protection'] = options.storage
    }

    // Skip production setup in dev mode
    if (!nuxt.options.dev) {
      // Detect platform at build time (reuse nitroPreset from above)
      // const nitroPreset = await resolveNitroPreset(nuxt) - already declared above
      const isCloudflareRuntime = nitroPreset?.includes('cloudflare')
      const isVercel = nitroPreset?.includes('vercel') || process.env.VERCEL_SKEW_PROTECTION_ENABLED === '1'
      const isStatic = isStaticPreset(nuxt)

      // Determine resolved strategy
      const isAdapter = isSkewAdapter(options.updateStrategy)
      let resolvedStrategy: 'polling' | 'sse' | 'ws' | 'adapter' = 'polling'

      if (isAdapter) {
        resolvedStrategy = 'adapter'
      }
      else if (options.updateStrategy === 'ws') {
        resolvedStrategy = 'ws'
      }
      else if (options.updateStrategy === 'sse') {
        resolvedStrategy = 'sse'
      }
      else if (!options.updateStrategy) {
        // Auto-detect: static = polling, cloudflare = ws, otherwise sse
        resolvedStrategy = isStatic ? 'polling' : isCloudflareRuntime ? 'ws' : 'sse'
      }

      // Validate strategy compatibility with static generation
      if (isStatic && resolvedStrategy !== 'polling' && resolvedStrategy !== 'adapter') {
        logger.warn(`Strategy "${resolvedStrategy}" requires a server but static generation detected. Falling back to polling.`)
        resolvedStrategy = 'polling'
      }

      if (isVercel) {
        addServerHandler({
          handler: resolver.resolve('./runtime/server/middleware/vercel-skew'),
          middleware: true,
        })
      }

      if (options.cookie !== false) {
        addServerHandler({
          handler: resolver.resolve('./runtime/server/middleware/set-skew-protection-cookie'),
          middleware: true,
        })
      }

      addPlugin({
        src: resolver.resolve('./runtime/app/plugins/sw-track-user-modules.client'),
        mode: 'client',
      })

      // allow us to use the non-transpiled version of the service worker from the module or root dir
      let swPath = resolver.resolve('./sw')
      if (!existsSync(swPath)) {
        // fallback to root dir
        swPath = resolver.resolve('../sw')
      }
      // Add service worker as public asset
      nuxt.options.nitro = nuxt.options.nitro || {}
      nuxt.options.nitro.publicAssets = nuxt.options.nitro.publicAssets || []
      nuxt.options.nitro.publicAssets.push({
        dir: swPath,
        maxAge: 0, // Service workers should not be cached
      })

      // Add build hooks for asset versioning (skip if bundling is disabled)
      if (options.storage && options.bundlePreviousDeploymentChunks) {
        nuxt.hook('nitro:init', (nitro) => {
          const buildId = nuxt.options.runtimeConfig.app.buildId ||= nuxt.options.buildId
          let assetManager: ReturnType<typeof createAssetManager>

          // Process assets before rollup finalization
          nitro.hooks.hook('compiled', async () => {
            const outputDir = nitro.options.output.dir

            assetManager = createAssetManager({
              ...options,
              driver: await resolveBuildTimeDriver(options.storage!),
            })

            // Get list of assets from build
            const assets = await assetManager.getAssetsFromBuild(outputDir)

            // Update versions manifest
            const { isExistingVersion } = await assetManager.updateVersionsManifest(buildId, assets)

            // Get release info for logging
            const manifest = await assetManager.getManifest()
            const totalReleases = Object.keys(manifest.versions).length
            const timestamps = Object.values(manifest.versions).map(v => new Date(v.timestamp).getTime())
            const oldestTimestamp = Math.min(...timestamps)
            const daysSince = Math.floor((Date.now() - oldestTimestamp) / (1000 * 60 * 60 * 24))
            const timeInfo = daysSince > 0 ? `${daysSince} day${daysSince > 1 ? 's' : ''} ago` : 'today'

            // Store assets in configured storage (can be slow with many assets)
            const storageInfo = options.storage!.base
              ? `${colors.green(options.storage!.driver)} ${colors.gray(`(${options.storage!.base})`)}`
              : colors.green(options.storage!.driver)
            if (totalReleases === 1) {
              logger.warn(`No previous versions found in storage. This is either the first deployment or storage is misconfigured. https://nuxtseo.com/docs/skew-protection/storage-configuration`)
            }
            else {
              logger.log(`Storing ${colors.yellow(assets.length.toString())} assets for ${colors.cyan(buildId.slice(0, 8))} (${totalReleases} releases, oldest from ${timeInfo}) [${storageInfo}]`)
            }

            await assetManager.storeAssetsInStorage(buildId, outputDir, assets)
              .catch((error: unknown) => {
                logger.error(`Failed to store assets:`, error instanceof Error ? error.message : error)
                throw error
              })

            // Count versions (excluding current)
            const existingVersions = await assetManager.listExistingVersions()
            const versionCount = existingVersions.filter(v => v.id !== buildId).length

            logger.success(`Successfully stored ${assets.length} assets for latest release`)

            // For static/prerendered builds: restore old versioned assets into public directory
            if (versionCount > 0) {
              // Re-read manifest after storeAssetsInStorage to get post-deduplication counts
              const updatedManifest = await assetManager.getManifest()
              let totalAssets = 0
              const versionSizes: string[] = []

              for (const [vId, vData] of Object.entries(updatedManifest.versions)) {
                if (vId !== buildId) {
                  totalAssets += vData.assets.length
                  versionSizes.push(`${vId.slice(0, 8)}:${vData.assets.length}`)
                }
              }

              logger.log(`Restoring build files from ${versionCount} release${versionCount > 1 ? 's' : ''} (${totalAssets} assets) [${versionSizes.join(', ')}]...`)
            }

            await assetManager.restoreOldAssetsToPublic(buildId, outputDir, assets, isExistingVersion)

            // Augment Nuxt build metadata files with skew protection data
            await assetManager.augmentBuildMetadata(buildId, outputDir)
          })

          // Clean up expired versions on close
          nitro.hooks.hook('close', async () => {
            if (assetManager) {
              await assetManager.cleanupExpiredVersions()
            }
          })
        })
      }

      // Register update strategy plugins
      if (resolvedStrategy === 'adapter' && isAdapter) {
        const adapter = options.updateStrategy as SkewAdapter
        // Store serializable adapter info
        // @ts-expect-error extending runtime config
        nuxt.options.runtimeConfig.public.skewProtection.adapterName = adapter.name

        // Validate adapter config at build time using zod schema
        const result = adapter.schema.safeParse(adapter.config)
        if (!result.success) {
          const errors = result.error.issues.map(i => `${i.path.join('.')}: ${i.message}`).join(', ')
          throw new Error(`${adapter.name} adapter config invalid: ${errors}`)
        }

        // Check for adapter dependencies at build time
        if (adapter.name === 'pusher') {
          if (!await tryResolveModule('pusher-js', nuxt.options.rootDir)) {
            const msg = `The pusher adapter requires \`pusher-js\`. Install with: npx nypm add pusher-js`
            if (!nuxt.options.dev && !nuxt.options._prepare) {
              throw new Error(msg)
            }
            else {
              logger.warn(msg)
            }
          }
        }
        else if (adapter.name === 'ably') {
          if (!await tryResolveModule('ably', nuxt.options.rootDir)) {
            const msg = `The ably adapter requires \`ably\`. Install with: npx nypm add ably`
            if (!nuxt.options.dev && !nuxt.options._prepare) {
              throw new Error(msg)
            }
            else {
              logger.warn(msg)
            }
          }
        }

        // Create template that imports from the actual adapter module (web build for client)
        const template = addTemplate({
          filename: 'skew-adapter.mjs',
          getContents: () => `import { subscribe } from 'nuxt-skew-protection/adapters/${adapter.name}/web'
export const config = ${JSON.stringify(adapter.config)}
export { subscribe }`,
        })
        nuxt.options.alias['#skew-adapter'] = template.dst

        addPlugin({
          src: resolver.resolve('./runtime/app/plugins/check-updates-adapter.client'),
          mode: 'client',
        })

        // Broadcast version update after build completes (not dev/prepare)
        if (!nuxt.options.dev && !nuxt.options._prepare) {
          nuxt.hook('close', async () => {
            const buildId = nuxt.options.runtimeConfig.app.buildId || nuxt.options.buildId
            const channel = (adapter.config as { channel?: string }).channel || 'skew-protection'
            logger.log(`Broadcasting update ${colors.cyan(buildId.slice(0, 8))} via ${colors.green(adapter.name)} (channel: ${colors.gray(channel)})`)

            let broadcastFn: BroadcastFn<any>
            switch (adapter.name) {
              case 'pusher': {
                const { broadcast } = await import('./runtime/adapters/pusher/node')
                broadcastFn = broadcast
                break
              }
              case 'ably': {
                const { broadcast } = await import('./runtime/adapters/ably/node')
                broadcastFn = broadcast
                break
              }
              default:
                logger.warn(`No broadcast implementation for adapter: ${adapter.name}`)
                return
            }

            await broadcastFn(adapter.config, buildId)
              .then(() => logger.success(`Broadcast complete`))
              .catch((err: Error) => logger.error(`Broadcast failed: ${err.message}`))
          })
        }
      }
      else if (resolvedStrategy === 'ws') {
        if (!nuxt.options.nitro?.experimental?.websocket) {
          logger.warn('You need to enable `experimental.websocket` in your Nitro config to use WebSockets. Falling back to polling.')
        }
        else if (isCloudflareRuntime && nitroPreset !== 'cloudflare-durable') {
          logger.warn('Websockets are only supported in Cloudflare using `cloudflare-durable` preset. Falling back to polling.')
        }
        else {
          addServerHandler({
            route: '/_skew/ws',
            handler: resolver.resolve('./runtime/server/routes/_skew/ws'),
          })
          addPlugin(resolver.resolve('./runtime/app/plugins/check-updates-websocket.client'))
        }
      }
      else if (resolvedStrategy === 'sse') {
        if (isCloudflareRuntime) {
          logger.warn('SSE not supported on Cloudflare Workers (no persistent connections). Falling back to polling.')
        }
        else {
          addServerHandler({
            route: '/_skew/sse',
            handler: resolver.resolve('./runtime/server/routes/_skew/sse'),
          })
          addPlugin({
            src: resolver.resolve('./runtime/app/plugins/check-updates-sse.client'),
            mode: 'client',
          })
        }
      }
    }
  },
})
